/**
 * bejwld catalog — the real launch capsule (25 pickleball pieces).
 *
 * This is the ONLY file that hard-codes product records. In production this data
 * lives in Shopify (products, collections, metafields, images) and this file is
 * deleted; `app/lib/catalog/index.ts` is rewritten to query the Storefront API.
 * Nothing else reads `PRODUCTS` directly — everything goes through the provider
 * in `index.ts`, so the swap is contained.
 *
 * Generated from the vendor price sheet + the render folders; imagery lives at
 * `/public/products/<imageDir>/<colour>/<view>-<size>.webp`.
 */

import type {Product, Sport} from './types';

/** The launch capsule — 25 pickleball pieces, in white and yellow gold. */
const PICKLEBALL: Product[] = [
  {
    handle: 'first-serve',
    name: 'First Serve',
    type: 'Pendant',
    initial: 'F',
    sport: 'pickleball',
    tier: 'gateway',
    price: 410,
    metal: '14k',
    stone: 'none',
    occasion: 'everyday',
    materials: '14k gold · polished',
    description: 'A first piece — the ball, in plain polished gold, worn close.',
    imageDir: 'p-pickle-b-p8110',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top'],
  },
  {
    handle: 'the-dink',
    name: 'The Dink',
    type: 'Pendant',
    initial: 'D',
    sport: 'pickleball',
    tier: 'signature',
    price: 700,
    metal: '14k',
    stone: 'accent',
    occasion: 'everyday',
    materials: '14k gold · 13 diamonds · 0.26 ct',
    description: 'The soft touch that wins the point — thirteen diamonds set flush in a gold sphere.',
    imageDir: 'gbp2809-p8113',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top'],
  },
  {
    handle: 'the-rally',
    name: 'The Rally',
    type: 'Pendant',
    initial: 'R',
    sport: 'pickleball',
    tier: 'signature',
    base: 430,
    configurable: true,
    metal: '14k',
    stone: 'accent',
    occasion: 'everyday',
    materials: '14k gold · 13 diamonds · 0.52 ct',
    description: 'Point after point — the ball carried in brighter fire.',
    badge: 'Made to order',
    imageDir: 'gbp2810-p8114',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top'],
  },
  {
    handle: 'the-ace',
    name: 'The Ace',
    type: 'Pendant',
    initial: 'A',
    sport: 'pickleball',
    tier: 'signature',
    base: 510,
    configurable: true,
    metal: '14k',
    stone: 'accent',
    occasion: 'gift',
    materials: '14k gold · 13 diamonds · 0.72 ct',
    description: 'Won outright. The ball, a half-carat further.',
    badge: 'Made to order',
    imageDir: 'gbp2811-p8124',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top'],
  },
  {
    handle: 'match-point',
    name: 'Match Point',
    type: 'Pendant',
    initial: 'M',
    sport: 'pickleball',
    tier: 'signature',
    price: 1030,
    metal: '14k',
    stone: 'pave',
    occasion: 'victory',
    materials: '14k gold · 13 diamonds · 1.05 ct',
    description: 'The piece the house was founded on — a full carat, held in a single sphere.',
    badge: 'The signature',
    imageDir: 'gbp2812-p8109',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top'],
  },
  {
    handle: 'first-serve-studs',
    name: 'First Serve Studs',
    type: 'Stud earrings',
    initial: 'F',
    sport: 'pickleball',
    tier: 'gateway',
    price: 320,
    metal: '14k',
    stone: 'none',
    occasion: 'everyday',
    materials: '14k gold · polished',
    description: 'The ball, twice and small, in plain gold at the ear.',
    imageDir: 'epickleb-p-e5588',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top', 'single'],
  },
  {
    handle: 'first-serve-drops',
    name: 'First Serve Drops',
    type: 'Drop earrings',
    initial: 'F',
    sport: 'pickleball',
    tier: 'gateway',
    price: 465,
    metal: '14k',
    stone: 'none',
    occasion: 'everyday',
    materials: '14k gold · polished',
    description: 'The ball, set swinging — plain gold on a fine hook.',
    imageDir: 'epickleb-e5585',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top', 'single'],
  },
  {
    handle: 'rally-studs',
    name: 'Rally Studs',
    type: 'Stud earrings',
    initial: 'R',
    sport: 'pickleball',
    tier: 'signature',
    price: 820,
    metal: '14k',
    stone: 'accent',
    occasion: 'gift',
    materials: '14k gold · 26 diamonds · 0.52 ct',
    description: 'A pair of diamond-set spheres, kept close to the ear.',
    imageDir: 'gse0378-a-e5589',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top', 'single'],
  },
  {
    handle: 'rally-drops',
    name: 'Rally Drops',
    type: 'Drop earrings',
    initial: 'R',
    sport: 'pickleball',
    tier: 'signature',
    price: 1055,
    metal: '14k',
    stone: 'accent',
    occasion: 'gift',
    materials: '14k gold · 26 diamonds · 0.52 ct',
    description: 'The rally, set swinging — diamond spheres on a fine hook.',
    imageDir: 'gse0378-b-e5596',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top', 'single'],
  },
  {
    handle: 'ace-studs',
    name: 'Ace Studs',
    type: 'Stud earrings',
    initial: 'A',
    sport: 'pickleball',
    tier: 'signature',
    price: 880,
    metal: '14k',
    stone: 'accent',
    occasion: 'gift',
    materials: '14k gold · 26 diamonds · 0.78 ct',
    description: 'The ace, worn as a pair — brighter, closer.',
    imageDir: 'gse0379-a-e5597',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top', 'single'],
  },
  {
    handle: 'ace-drops',
    name: 'Ace Drops',
    type: 'Drop earrings',
    initial: 'A',
    sport: 'pickleball',
    tier: 'signature',
    price: 1100,
    metal: '14k',
    stone: 'accent',
    occasion: 'gift',
    materials: '14k gold · 26 diamonds · 0.78 ct',
    description: 'The ace in motion — diamond spheres that catch the light.',
    imageDir: 'gse0379-b-e5586',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top', 'single'],
  },
  {
    handle: 'match-point-studs',
    name: 'Match Point Studs',
    type: 'Stud earrings',
    initial: 'M',
    sport: 'pickleball',
    tier: 'signature',
    price: 950,
    metal: '14k',
    stone: 'pave',
    occasion: 'victory',
    materials: '14k gold · 26 diamonds · 1.04 ct',
    description: 'The closing point, in a pair — a full carat across two spheres.',
    imageDir: 'gse0380-a-e5590',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top', 'single'],
  },
  {
    handle: 'match-point-drops',
    name: 'Match Point Drops',
    type: 'Drop earrings',
    initial: 'M',
    sport: 'pickleball',
    tier: 'signature',
    price: 1195,
    metal: '14k',
    stone: 'pave',
    occasion: 'victory',
    materials: '14k gold · 26 diamonds · 1.04 ct',
    description: 'Match point, set swinging — the win, worn to the ear.',
    imageDir: 'gse0380-b-e5587',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top', 'single'],
  },
  {
    handle: 'the-baseline',
    name: 'The Baseline',
    type: 'Pendant',
    initial: 'B',
    sport: 'pickleball',
    tier: 'signature',
    base: 365,
    configurable: true,
    metal: '14k',
    stone: 'pave',
    occasion: 'everyday',
    materials: '14k gold · 96 diamonds · 0.67 ct',
    description: 'The court in pavé — every line drawn in diamond.',
    badge: 'Made to order',
    imageDir: 'asp0420-p8111',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top'],
  },
  {
    handle: 'the-sideline',
    name: 'The Sideline',
    type: 'Pendant',
    initial: 'S',
    sport: 'pickleball',
    tier: 'signature',
    price: 795,
    metal: '14k',
    stone: 'pave',
    occasion: 'everyday',
    materials: '14k gold · 96 diamonds · 0.67 ct',
    description: 'The court, drawn a little finer — the same pavé, closer in.',
    imageDir: 'gsp0511-p8112',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top'],
  },
  {
    handle: 'the-kitchen',
    name: 'The Kitchen',
    type: 'Pendant',
    initial: 'K',
    sport: 'pickleball',
    tier: 'gateway',
    price: 545,
    metal: '14k',
    stone: 'none',
    occasion: 'everyday',
    materials: '14k gold · polished',
    description: 'The court in open gold — the non-volley line, kept plain.',
    imageDir: 'fw-pickleball-court-plain-p8120',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top'],
  },
  {
    handle: 'center-court',
    name: 'Center Court',
    type: 'Pendant',
    initial: 'C',
    sport: 'pickleball',
    tier: 'gateway',
    price: 545,
    metal: '14k',
    stone: 'none',
    occasion: 'everyday',
    materials: '14k gold · polished',
    description: 'The court, framed in polished gold.',
    imageDir: 'gsp0510-p8119',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top'],
  },
  {
    handle: 'center-court-enamel',
    name: 'Center Court, Enamel',
    type: 'Pendant',
    initial: 'C',
    sport: 'pickleball',
    tier: 'statement',
    price: 1925,
    metal: '14k',
    stone: 'pave',
    occasion: 'gift',
    materials: '14k gold · 103 diamonds · 0.72 ct',
    description: 'The court in blue-and-green enamel, edged all around in pavé.',
    imageDir: 'gsp0483-p8121',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top'],
  },
  {
    handle: 'the-kitchen-enamel',
    name: 'The Kitchen, Enamel',
    type: 'Pendant',
    initial: 'K',
    sport: 'pickleball',
    tier: 'signature',
    price: 995,
    metal: '14k',
    stone: 'none',
    occasion: 'gift',
    materials: '14k gold · polished',
    description: 'The court in enamel — blue, green, and gold, no stones.',
    imageDir: 'gsp0484-p8122',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top'],
  },
  {
    handle: 'championship-court',
    name: 'Championship Court',
    type: 'Pendant',
    initial: 'C',
    sport: 'pickleball',
    tier: 'statement',
    base: 6215,
    configurable: true,
    metal: '14k',
    stone: 'pave',
    occasion: 'victory',
    materials: '14k gold · 12 diamonds · 8.08 ct',
    description: 'The court in baguettes — eight carats, laid like lines of play.',
    badge: 'Numbered',
    imageDir: 'gbp2815-p8107',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top'],
  },
  {
    handle: 'championship-court-full',
    name: 'Championship Court, Full',
    type: 'Pendant',
    initial: 'C',
    sport: 'pickleball',
    tier: 'statement',
    price: 7310,
    metal: '14k',
    stone: 'pave',
    occasion: 'victory',
    materials: '14k gold · 80 diamonds · 9.2 ct',
    description: 'The court, fully set — baguette and pavé, nine carats and change.',
    badge: 'Numbered',
    imageDir: 'gbp2815-diamond-version-p8123',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top'],
  },
  {
    handle: 'the-paddle',
    name: 'The Paddle',
    type: 'Pendant',
    initial: 'P',
    sport: 'pickleball',
    tier: 'gateway',
    price: 605,
    metal: '14k',
    stone: 'none',
    occasion: 'everyday',
    materials: '14k gold · polished',
    description: 'The paddle in silhouette, polished smooth.',
    imageDir: 'jfp1395-p8117',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top'],
  },
  {
    handle: 'the-paddle-brushed',
    name: 'The Paddle, Brushed',
    type: 'Pendant',
    initial: 'P',
    sport: 'pickleball',
    tier: 'gateway',
    price: 625,
    metal: '14k',
    stone: 'none',
    occasion: 'everyday',
    materials: '14k gold · polished',
    description: 'The paddle, its face brushed — grip and all.',
    imageDir: 'jfp1400-p8116',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top'],
  },
  {
    handle: 'the-paddle-pave',
    name: 'The Paddle, Pavé',
    type: 'Pendant',
    initial: 'P',
    sport: 'pickleball',
    tier: 'signature',
    base: 460,
    configurable: true,
    metal: '14k',
    stone: 'pave',
    occasion: 'gift',
    materials: '14k gold · 105 diamonds · 0.64 ct',
    description: 'The paddle, its face in pavé — a hundred stones, held flat.',
    badge: 'Made to order',
    imageDir: 'jfp1394-p8108',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top'],
  },
  {
    handle: 'the-paddle-full-pave',
    name: 'The Paddle, Full Pavé',
    type: 'Pendant',
    initial: 'P',
    sport: 'pickleball',
    tier: 'signature',
    price: 1350,
    metal: '14k',
    stone: 'pave',
    occasion: 'victory',
    materials: '14k gold · 119 diamonds · 0.72 ct',
    description: 'The paddle, set edge to edge — the whole face in diamond.',
    imageDir: 'paddle-p8118',
    colours: ['yellow', 'white'],
    views: ['cutout', '3d', 'front', 'right', 'top'],
  },
];

/**
 * The second capsule — proof the model is sport-agnostic. Not part of the
 * launch; surfaced only when `BEJWLD_ENABLE_TENNIS=true`. In production this is
 * simply a `tennis` collection with tagged products, published from admin.
 */
const TENNIS: Product[] = [
  {
    handle: 'deuce',
    name: 'Deuce',
    type: 'Pendant',
    initial: 'D',
    sport: 'tennis',
    tier: 'gateway',
    price: 340,
    metal: 'vermeil',
    stone: 'none',
    occasion: 'everyday',
    materials: 'Gold vermeil · racket-string hairlines',
    description: 'Even, again. The score that keeps the evening going.',
  },
  {
    handle: 'advantage',
    name: 'Advantage',
    type: 'Pavé studs',
    initial: 'A',
    sport: 'tennis',
    tier: 'signature',
    base: 1050,
    configurable: true,
    metal: '14k',
    stone: 'pave',
    occasion: 'gift',
    materials: '14k gold · pavé-set spheres',
    description: 'One point ahead, and dressed for it.',
    badge: 'Configurable',
  },
  {
    handle: 'grand-slam',
    name: 'Grand Slam',
    type: 'Necklace',
    initial: 'G',
    sport: 'tennis',
    tier: 'statement',
    price: 5400,
    metal: '18k',
    stone: 'pave',
    occasion: 'victory',
    materials: '18k gold · four diamond markers',
    description: 'Four courts, one chain. For a season worth remembering.',
  },
];

/**
 * The full product set for this environment. Reads the tennis flag once, at
 * module load, from a Vite-inlined env var (`VITE_BEJWLD_ENABLE_TENNIS`) so it
 * resolves identically in Node and in the Oxygen worker. In production, remove
 * this and query the Storefront API.
 */
const ENABLE_TENNIS =
  (import.meta.env?.VITE_BEJWLD_ENABLE_TENNIS as string | undefined) === 'true';

export const PRODUCTS: Product[] = ENABLE_TENNIS
  ? [...PICKLEBALL, ...TENNIS]
  : [...PICKLEBALL];

/**
 * Editorial copy per sport. In production this is a metaobject / collection
 * description keyed by handle; unknown sports fall back gracefully.
 */
export const SPORT_META: Record<
  Sport,
  {tagline: string; description: string}
> = {
  pickleball: {
    tagline: 'The launch capsule',
    description:
      'Twenty-five pieces for the fastest-growing game in America — the ball as a diamond-set sphere, the court in pavé and enamel, the paddle in silhouette.',
  },
  tennis: {
    tagline: 'The second capsule',
    description: 'Lawn whites and yellow gold — the score kept in diamonds.',
  },
};
